# Generated by Django 2.0.5 on 2019-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospital',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
