# Generated by Django 2.0.5 on 2019-04-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190416_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='userblocks',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='userblocks',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-'), ('AB+', 'AB+')], default='a+', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Donor', 'Donor'), ('Receiver', 'Receiver')], default='receiver', max_length=10),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
        migrations.DeleteModel(
            name='UserBlocks',
        ),
    ]
